### ISSUE TITLE
Still no video with libreelec

### ISSUE THREAD

**Issue by He4dnut** [dead/moonlight-openelec-rpi2#35]
Hi, 
i still dont get the video in moonlight working. Sound and controller ist working. I installed moonlight 7.0.104 from the libreelec repo. The addon description says it is moonlight version 2.2.2. Did somebody forget to refresh the description text or is this realy not the newest version 2.2.3 with the video fix?
By the way. I'm using the newest libreelec version 7.0.3 and GFE 3.2.0.96. 
Thank you in advance!

**Comment by kognor1982** [comment]
Hi
I'm also having this issue.  Audio streaming works.  Libreelect version 7.0.3, GFE 3.2.2.49, and the moonlight addon from the libreelec repo.

Can you assist?  or fix this issue?

Thanks in advance!

**Comment by 4noxx** [comment]
same problem.
use GeForce_Experience_v2.11.4.0
other Clients like Android or Recalbox works fine. 
get this log from LE v7.95.1 BETA/Moonlight 

Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
done
Starting audio stream...done
Starting input stream...done
Decode failed - Invalid data found when processing input
Decode failed - Invalid data found when processing input
Decode failed - Invalid data found when processing input
Decode failed - Invalid data found when processing input
Decode failed - Invalid data found when processing input
Decode failed - Invalid data found when processing input
....

use a x64 HTPC

**Comment by NoHacks** [comment]
still the same problem..
Moonlight v7.0.104 from LibreELEC Repo
GeForce Experience v3.3.0.95

**Comment by florianjacob** [comment]
Same here, using Libreelec 7.95.2 BETA.

**Comment by florianjacob** [comment]
Other log messages, though:
```
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...done
Starting input stream...done
Returning RTP packet queued for too long
Network dropped middle of a frame
Returning RTP packet queued for too long
Returning RTP packet queued for too long
Returning RTP packet queued for too long
Returning RTP packet queued for too long
Waiting for IDR frame
Waiting for IDR frame
IDR frame request sent
Waiting for IDR frame
Waiting for IDR frame
Returning RTP packet queued for too long
Network dropped middle of a frame
Returning RTP packet queued for too long
Returning RTP packet queued for too long
Returning RTP packet after queue overgrowth
Waiting for IDR frame
IDR frame request sent
Waiting for IDR frame
Waiting for IDR frame
Returning RTP packet queued for too long
Network dropped middle of a frame
Returning RTP packet queued for too long
Returning RTP packet queued for too long
Returning RTP packet after queue overgrowth
Waiting for IDR frame
IDR frame request sent
Waiting for IDR frame
Waiting for IDR frame
Returning RTP packet queued for too long
Network dropped middle of a frame
Returning RTP packet queued for too long
Returning RTP packet queued for too long
Returning RTP packet queued for too long

…

Returning RTP packet after queue overgrowth
Returning RTP packet queued for too long
Network dropped middle of a frame
Returning RTP packet queued for too long
Returning RTP packet after queue overgrowth
Waiting for IDR frame
IDR frame request sent
Returning RTP packet queued for too long
Received OOS audio data (expected 4211, but got 4212)
Waiting for IDR frame
Waiting for IDR frame
Returning RTP packet queued for too long
Network dropped middle of a frame
Returning RTP packet queued for too long
Control stream received disconnect event
Loss Stats: Transaction failed: 11
Stopping input stream...done
Stopping audio stream...done
Stopping video stream...done
Stopping control stream...done
Cleaning up input stream...done
Cleaning up audio stream...done
Cleaning up video stream...done
Cleaning up control stream...done
Terminating RTSP handshake...done
Cleaning up platform...done
Moonlight Embedded 2.2.2 (SDL;EMBEDDED;PULSE;CEC;PI)
Searching for server...
Connect to 192.168.178.84...
NVIDIA GeForce GTX 750 Ti, GFE 3.3.0.95 (protocol version 7)
Stream 1280 x 720, 30 fps, 10000 kbps
```
